services:
  app:
    build: .
    ports:
      - '4000:4000'
    environment:
      PORT: 4000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
